<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Bharathwaj" name="week5day1hw.MergeLeadUsingTestNG" tests="1" failures="0" timestamp="01 May 2018 15:45:23 GMT" time="59.049" errors="1">
  <testcase name="run" time="59.049" classname="week5day1hw.MergeLeadUsingTestNG">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat wdMethods.SeMethods.clickWithNoSnap(SeMethods.java:119)at week5day1hw.MergeLeadUsingTestNG.run(MergeLeadUsingTestNG.java:45)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:278)at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:265)at org.testng.internal.Invoker.invokeMethod(Invoker.java:577)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- run -->
</testsuite> <!-- week5day1hw.MergeLeadUsingTestNG -->
